# Generated by Django 6.0.5 on 2026-05-25 06:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=64)),
                ('region', models.CharField(default='India', max_length=64)),
                ('unit', models.CharField(max_length=32)),
                ('factor_kgco2e', models.FloatField()),
                ('source_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=32)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Electricity'), ('SCOPE_3', 'Scope 3 — Value Chain')], max_length=16)),
                ('category', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity_raw', models.FloatField()),
                ('unit_raw', models.CharField(max_length=32)),
                ('quantity_norm', models.FloatField()),
                ('unit_norm', models.CharField(max_length=32)),
                ('co2e_kg', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=16)),
                ('flagged_reason', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.client')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.emissionfactor')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=64)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.emissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plant_code', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(default='India', max_length=64)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingestion.client')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_CONCUR', 'Corporate Travel')], max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('ingested_by', models.CharField(default='analyst', max_length=255)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.client')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.facility')),
            ],
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('OK', 'OK'), ('FAILED', 'Failed'), ('SUSPICIOUS', 'Suspicious')], default='OK', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.ingestionbatch')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_row',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.rawrow'),
        ),
    ]
